version: '3.1'
services:
    database:
        image: 'mariadb:10'
        container_name: lychee_db
        working_dir: /var/www
        volumes:
            - '${LYCHEE_PROJECT_PATH}:/var/www'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - '${DB_PORT}:3306'
        networks:
          - lychee
        restart: unless-stopped

    nginx:
        build: nginx
        container_name: lychee_nginx
        working_dir: /var/www
        volumes:
            - '${LYCHEE_PROJECT_PATH}:/var/www'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${NGINX_PORT}:80'
        networks:
          - lychee
        restart: unless-stopped

    php-fpm:
        build: php-fpm
        container_name: lychee_php
        working_dir: /var/www
        user: 1000:1000
        volumes:
            - '${LYCHEE_PROJECT_PATH}:/var/www'
            - './php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=database
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - LYCHEE_UPLOADS=${LYCHEE_UPLOADS}
            - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        networks:
          - lychee
        restart: unless-stopped

networks:
    lychee:
        name: lychee_network

volumes:
    db_data:
